### ISSUE TITLE
CSS Transitions Problem

### ISSUE THREAD

**Issue by themikesnow** [marcj/css-element-queries#101]
There seems to be a problem with the CSS transitions. For some reason if I start from the small size window to a bigger size the min-width attribute values are added to the element and the CSS are applied correctly. But if I change/resize from a big size window to small window  the min-width attributes are not updated, it the keeps min-width="1200px 750px" and the value. Below you can find the CSS I am using. 

.station .station-bay{
    @extend .col-xs-12;
}
.station[min-width~="750px"] .station-bay{
    @extend .col-xs-6;
}
.station[min-width~="1200px"] .station-bay{
    @extend .col-xs-4;
}

**Comment by marcj** [comment]
Which version are you using? Have you tried master and 0.3.2? Please try both.

**Comment by miguelnievesacevedo** [comment]
I was using version 0.3.2 from npm and just tried the master with no luck (issue is still showing up). BTW, I am using your polyfill with reactjs, not sure if that will have any impact.

**Comment by marcj** [comment]
Mh, yeah I guess react has a big impact on that since it modifies the DOM dynamically. But it shouldnt work then in general not only one way. So I guess its related to the resize sensor. In which browser does this happen?

**Comment by miguelnievesacevedo** [comment]
Actually, it works sometimes, I mean in other places of the application. I have tested the issue on Chrom and IE. Does using init has any side effects? instead of listen? Init has never worked for me, I need to call init on the react components to make it work.

**Comment by marcj** [comment]
Well, if it works not everywhere then I guess its related to react, perhaps it did change some DOM and therefore break the sensor. Using `ElementQueries.init()` should fix that. How did you hook into React DOM changes events?

**Comment by miguelnievesacevedo** [comment]
Inside the componentDidMount event.
