### ISSUE TITLE
ElementQueries can't read cross-origin stylesheets

### ISSUE THREAD

**Issue by eschatonic** [marcj/css-element-queries#102]
We're using a CDN to host our stylesheets, unfortunately this appears to prevent ElementQueries from working.

It seems that when using stylesheets on an alternate domain, the .cssRules and .rules properties of those stylesheets are not accessible due to cross-origin issues (cf. http://stackoverflow.com/q/5678040), meaning that the readRules() function simply skips the stylesheet.

For some reason this appears to affect latest Firefox and Chrome but not Internet Explorer 11.

Here's an example of an affected stylesheet's property list.
![cssrulesnull](https://cloud.githubusercontent.com/assets/1318441/13985021/0320fb7a-f0f2-11e5-8541-2429d19f7f8b.PNG)

I understand from https://github.com/marcj/css-element-queries/issues/16 that there is currently no support for loading cross-domain resources; is this still the case?

**Comment by marcj** [comment]
Yes, unfortunately Browser don't accept that. You can try to set the `Access-Control-Allow-Origin` header on your CDN, to allow your actual website to read all resources from that CDN. https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by DrDeath72** [comment]
`Access-Control-Allow-Origin` didn't help :(
