### ISSUE TITLE
Does this work with relative (em, %) units?

### ISSUE THREAD

**Issue by coreyworrell** [marcj/css-element-queries#103]
The demo site is setup using pixel units so I can't tell if it does.

For example, say you have a `div` with its width set to `20em`. With the default browser font size settings, that will result in a width of `320px`. But if you have your browser set to a default font size of say `20px`, then that same div would report its width as `400px`. So any selectors you were using before would be invalid.

**Comment by marcj** [comment]
The sensor itself return always the dimensions as pixels. Element-queries converts then your em in the css rule to pixel and compare it. However, I've never used em rules, so feel free to test and send us your feedback. :-)
