### ISSUE TITLE
Only works when I resize the page?

### ISSUE THREAD

**Issue by seafarer** [marcj/css-element-queries#105]
Kind of a js noob, but how can I get fire the ResizeSensor when the page loads? Right now it only works when I resize the page. Here is my code

```
if($('.activity-grid').length) {

    var baseEl = $('.activity-grid__item--5');
    var baseHeight = baseEl.outerHeight(true);

    new ResizeSensor(baseEl, function(){
       $('.activity-grid__item--5').css({ 'margin-top': '-' + baseHeight + 'px' });
       $('.activity-grid__item--6').css({ 'margin-top': '-' + baseHeight + 'px' });
    })
 }
```

**Comment by marcj** [comment]
Why should the resizeSensor fire when the page loads?

**Comment by seafarer** [comment]
Haha. Ok. Right. Sorry for a moment of density. I got it now.

On Wed, May 4, 2016 at 3:44 PM Marc J. Schmidt <notifications@github.com>
wrote:

> Why should the resizeSensor fire when the page loads?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/marcj/css-element-queries/issues/105#issuecomment-217013031>
>
-- 
===
Colin OBrien

Develody | A harmony of code and creative
www.develody.io | 970.404.0988

**Comment by marcj** [comment]
hehe ok :P
