### ISSUE TITLE
"Less" compatibility

### ISSUE THREAD

**Issue by hpvd** [marcj/css-element-queries#112]
Would be great to have an working example where
css element queries works nicely in combination with  CSS pre-processor "Less" .
One first idea could be to use Less' Variable function for some "global" definition of "min-width"

for other possibilities see
http://lesscss.org/features/

What do you think?

**Comment by marcj** [comment]
I don't get the point behind your request. css-element-queries is built upon regular css. Why do you think its necessary to have an example for less? The actual element query rule is not different to regular css. The only thing that is different are some less features, which have nothing to do with css-element-queries.
