### ISSUE TITLE
IE9 compatibility issue when using a VM

### ISSUE THREAD

**Issue by mattconvente** [marcj/css-element-queries#113]
Hi Marc,

I've been testing your demo site on IE9 in a VirtualBox VM from Modern.ie, and the element styles are not applying. I took a video of my browser test, which you can see here: http://recordit.co/m20osPJjtF

The element styles do work when I test on Edge and use the dev tools to emulate IE9. However, I also like to test in VMs to see if there are noticeable differences, as in this case.

Any ideas? Could it be my setup or something else?

Many thanks,
Matt

**Comment by marcj** [comment]
Thanks for reporting this! Could you also try to test against the latest release `0.3.2` ?

**Comment by mattconvente** [comment]
Wow, super quick reply! :) I'll try `0.3.2` locally; I've only done browser testing on your demo page thus far. Is your demo not on the latest?

**Comment by marcj** [comment]
The demo page is using the master branch. But I added lately some experimental stuff into master, thus there not tag for this yet. Latest stable is `0.3.2` so would be cool if you could check that version

**Comment by marcj** [comment]
Dropped IE9 support.
