### ISSUE TITLE
incompatibility with jQuery position() method

### ISSUE THREAD

**Issue by creative-resort** [marcj/css-element-queries#119]
Situation:
```
<div></div>
<section id="parent">
  <div id="child"></div>
  <div></div>
</section>
```
After applying the ResizeSensor to an element $("#parent"),
a child element's top position results in "0"
when checked with jQuery method
`$("#child").position().top`

This works correctly, however when ResizeSensor is applied to the child element itself.

**Comment by marcj** [comment]
Maybe because the resize sensor makes the element positioned relative (as stated in the readme)?

**Comment by creative-resort** [comment]
Thank you very much!
I need to use .offset() instead of .position()
