### ISSUE TITLE
no interval/timeout detection. Truly event-based through integrated ResizeSensor class.

### ISSUE THREAD

**Issue by bogdanpetru** [marcj/css-element-queries#123]
Hello,

I was looking through the code and found that there is a timeout (requestAnimationFrame), that continuously runs. It calls registered callbacks when is `dirty`. `dirty` seems to be set to true after node fires onScroll.

Am I missing something?

https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js#L156
```js
var dirty = false; 
var dirtyChecking = function() {
   if (!element.resizedAttached) return;

   if (dirty) {
       element.resizedAttached.call();
       dirty = false;
   }

   requestAnimationFrame(dirtyChecking);
};

requestAnimationFrame(dirtyChecking);
```

**Comment by marcj** [comment]
It is used to debounce all those high frequently events (for animations for example or drag'n'drop), so it limits calls per frame, meaning user land code gets only each animation frame max one call per listener. This has nothing to do with the actual resize detection.

**Comment by ryanlin1986** [comment]
Good point. @marcj
