### ISSUE TITLE
please separate ResizeSensor project in  dedicated github repo.

### ISSUE THREAD

**Issue by nasreddineskandrani** [marcj/css-element-queries#124]
Hi,
It's more a suggestion. I see around me that a lot of devs need only your work for ResizeSensor and not the rest of the repo. It will be good if you can separate ResizeSensor  in a separate github repo and from the repo "css-element-queries" get the .js file needed (dependecy in your package.json)

In my case, i am adding an event to ResizeSensor and i can't add it to this repo because i dont need to use all the other stuff. So i am doing that here:
https://github.com/nasreddineskandrani/DomResize

If you separate the ResizeSensor in a separate repo. i ll create a pull request when my job is done and i ll remove my own repo "DomResize"

Thank you

P.s. what other devs think about having ResizeSensor in isolated repo???

**Comment by marcj** [comment]
I really think its not worth the work. Just to have *one* file less (it's not like we are talking here about dozens of unnecessary files where I'd aggree) in your node_modules folder. Either way, you can simply exclude that file in your build process. We definitely not live in a time where diskspace is an issue anymore

**Comment by rask** [comment]
The resize sensor would be a great library on its own me thinks. I'm currently working on a scroll bar library and detecting element resizes with ResizeSensor is something I'm attempting. :)

**Comment by landabaso** [comment]
+1 on this one (even if it's closed).
I'm using webpack vendor bundles and I get ElementQueries in the bundle (which I don't use).
This would not be a big problem except for the error that ElementQueries throws (`Uncaught TypeError: Cannot set property 'ElementQueries' of undefined`" - same as in https://github.com/marcj/css-element-queries/issues/82).
