### ISSUE TITLE
Does not work with HTML Imports

### ISSUE THREAD

**Issue by dannyfritz** [marcj/css-element-queries#125]
I was playing with CSS Element Queries and Web Components and the scope of a `stylesheet` pulled into a `document` with an HTML import aren't on the main `document`. So when I use HTML Import to import my stylesheet, `ElementQueries.js` is unaware of the stylesheet.

http://www.html5rocks.com/en/tutorials/webcomponents/imports/#usingcontent

https://github.com/marcj/css-element-queries/blob/812e3bba36d5da3c955825925877dd2efa0679ff/src/ElementQueries.js#L385-L393

**Comment by potatogopher** [comment]
@dannyfritz Do you have a work around?

**Comment by dannyfritz** [comment]
I can't remember what the conclusion I came to was at the time, but I had decided it would not work. Something about the HTML Import context making it hard to break out of.

**Comment by dannyfritz** [comment]
Seems most browser vendors have concluded HTML Imports is not the future. Will close this out as web components now are going a different direction.
