### ISSUE TITLE
Resize events not firing when container gets smaller

### ISSUE THREAD

**Issue by jmwohl** [marcj/css-element-queries#132]
I have a container that stretches to fill the width of the screen. When I add element queries to it, the expected 'min-width' attributes are added to the DOM element on load and as I make the browser window _bigger_, but when I shrink the browser window back down the attributes are never removed. Adding a `ResizeSensor` to the element shows that it's firing change events as I increase the browser width, but not as I decrease it.

Am I missing something?

**Comment by marcj** [comment]
Demo to reproduce? browser? A bit more information would be useful, otherweise nobody is able to help you.

**Comment by jmwohl** [comment]
Browser is latest chrome. I'll try to post a demo, just hoping it was an obvious and/or common problem that someone may have an easy solution for.

**Comment by leevigraham** [comment]
@marcj @jmwohl,

Demo 

* using CSS animations
* chrome 57.0.2987.98

http://codepen.io/leevigraham/pen/evMQre (check console).

Relevant code is at the bottom of the JS window

**Comment by leevigraham** [comment]
@marcj @jmwohl,

I found the issue with my implementation. I was styling a div with a broad div selector. The div css rule set width, height and animation. The resize sensor was inheriting the broad css style.

**Comment by marcj** [comment]
Codepen link is invalid. Please check again with upcoming 1.0.0 version.
