### ISSUE TITLE
update npm package

### ISSUE THREAD

**Issue by landabaso** [marcj/css-element-queries#136]
Hi @marcj!

Thanks for this great package. I was going to create a new issue on improving performance but then I realized you already did some work with dirty checking + requestAnimationFrame.

The problem is that this improvement has not been reflected on the npm package yet.

Could you please upgrade it to include all the new tricks?

EDIT: Try to merge [this pull request](https://github.com/marcj/css-element-queries/pull/137) before updating if possible ;-): https://github.com/marcj/css-element-queries/pull/137

**Comment by marcj** [comment]
Done, thanks!
