### ISSUE TITLE
Size change not detected when initially-invisible parent container becomes visible

### ISSUE THREAD

**Issue by hbCyber** [marcj/css-element-queries#139]
Not sure if there's a work-around for this. Unfortunately I need to track resizes of containers that are within pop-up dialogs that are initially hidden. I need the ResizeSensor to fire when the parent pop-up container becomes visible, bringing the target container's offsetWidth from 0 to its actual width.

Here's a JS fiddle to reproduce the problem. In the fiddle, the container becomes visible after a 5s delay to simulate a pop-up appearing behaviour.

https://jsfiddle.net/yur7ms5g/

Additional note: in another experiment, if the parent container starts off as visible, then becomes invisible, and then becomes visible again, it seems that the ResizeSensor on the child element survives the process.

See JS fiddle:
https://jsfiddle.net/wv10gcbb/2/

Overall, the issue seems to be that ResizeSensor fails to bind/initialize if the parent container is invisible at the moment of creation specifically.

**Comment by hbCyber** [comment]
Additional note: in another experiment, if the parent container starts off as visible, then becomes invisible, and then becomes visible again, it seems that the ResizeSensor on the child element survives the process.

See JS fiddle:
https://jsfiddle.net/wv10gcbb/2/

Overall, the issue seems to be that ResizeSensor fails to bind/initialize if the parent container is invisible at the moment of creation specifically.

**Comment by Giwayume** [comment]
Probably the only way around this would be to have a setInterval that does a slow check to see when the element first becomes visible, then run the initialization code at that point.

**Comment by marcj** [comment]
I don't know yet a fast and cross-browser approach to know whether a elements becomes visible. Do you?

**Comment by Giwayume** [comment]
Depends on your definition of "visible". It's easy & fast to test for complete invisibility via `display:none`.

```
function isNodeVisible(node) {
    return !!( node.offsetWidth || node.offsetHeight || node.getClientRects().length );
}
```

However, if your definition of "invisible" also includes `visibility:hidden` and `opacity:0`, you have to loop up through the DOM and check each of the parent nodes for these styles. 

Luckily in your case, I don't believe `visibility:hidden` or `opacity:0` cause this issue.

**Comment by hbCyber** [comment]
Actually I have switched to another strategy which does work, i.e. tells me when an element becomes visible. It involves adding a child <object> element, and listening for the "onload" event. I found the original code in a blog post and modified it. Should I paste it somewhere?

**Comment by franktopel** [comment]
Sure!

**Comment by hbCyber** [comment]
Oh well, after testing, turns out it only works in Chrome. Other browsers must use setInterval() indeed. Still, here's the snippet:

```
                var obj = document.createElement('object');
                element.internalWidthTracker = obj;

                obj.setAttribute('style', 
                    'display: block;'
                    + 'position: absolute;'
                    + 'top: 0; left: 0;'
                    + 'height: 100%; width: 100%;'
                    + 'overflow: hidden;'
                    + 'pointer-events: none;'
                    + 'z-index: -1;');

                obj.parentWidthTrackerElement = element;
                obj.widthTrackerTrigger = function() {
                    // Your code here
                };
                
                // Trigger callback when object is loaded/shown
                if (document.attachEvent) {
                    obj.attachEvent("onload", obj.widthTrackerTrigger);
                }
                else {
                    obj.onload = obj.widthTrackerTrigger;
                }
                
                // If not Chrome, 'onload' callback is only called once.
                // We must rely on a timer to trigger the callback in case
                // the object's container became visible/invisible.
                if (!browserIsChrome) {
                    obj.widthTrackerTimer = setInterval(function() {
                        obj.widthTrackerTrigger();
                    }, CALLBACK_INTERVAL_MS);
                }

                obj.type = 'text/html';
                if (isIE) {
                    element.appendChild(obj);
                }

                obj.data = 'about:blank';
                if (!isIE) {
                    element.appendChild(obj);
                }`
```
