### ISSUE TITLE
Uncaught ReferenceError: module is not defined (for Rails Assets package)

### ISSUE THREAD

**Issue by Seally** [marcj/css-element-queries#143]
Rails Assets relies on bower.json to repackage Bower components as a gem. This file's removal in v0.4.0 seems to have caused this issue. Here's another component where the same issue happened: https://github.com/jackocnr/intl-tel-input/issues/372.

Can this file be re-added to the repository? I'll otherwise have to revert to 0.3.2 or add this library manually into the assets pipeline.

**Comment by marcj** [comment]
We do not support bower as it's basically useless.
