### ISSUE TITLE
IE9 Responsive Elements Not Working

### ISSUE THREAD

**Issue by aarongd** [marcj/css-element-queries#146]
Hey MarcJ,

The responsive elements on the demo page don't seem to be working in IE9. I also did some local tests with the same problem. It's fine in IE10+

I tested on Browserstack and an old laptop with IE9.

Any ideas of how to get it to work?

**Comment by marcj** [comment]
Heyho, can u test the current master version and try older releases https://github.com/marcj/css-element-queries/releases? Last time I tested it worked fine down to IE6.  Maybe we need to revert the changed of https://github.com/marcj/css-element-queries/commit/d96e17397c3fa3e6cea96b239ef02628169267f0#diff-78e9e3017ac87f0bf57e1ce8446df03eL87 to make it 100% sure it works in older IEs.

**Comment by aarongd** [comment]
Hmm, I can't seem to get any older release to work in IE9, but I might be doing something completely wrong.

I used your /test index files in Browserstack on IE9. Also, the 'resizable' handles disappear from index  0.3.1 onwards. All still seems fine in IE10+.

**Comment by marcj** [comment]
Do you get any error? Can create a jsfiddle?

**Comment by aarongd** [comment]
Doesn't seem to be any errors in IE9, just doesn't seem to be working. Yep, I will do.

**Comment by aarongd** [comment]
Codepen isn't supported by IE9 and you won't be able to test it in there. I've uploaded a zip file with the older Javascript in each folder. Hope this suits you.

[https://expirebox.com/download/5b47ed5c2dd934a946aa793a04082c1c.html](url)

**Comment by marcj** [comment]
Dropped IE9 support.
