### ISSUE TITLE
getComputedStyle can return null in Firefox

### ISSUE THREAD

**Issue by shapeshifta78** [marcj/css-element-queries#148]
Hey there,
we are using your resizeSensor inside an iframe which is surrounded by a tab. There is a bug in firefox which makes getComputedStyle return null in an iframe set to display:none. 
see https://bugzilla.mozilla.org/show_bug.cgi?id=548397

I modified your function like this, which seems to fix it:

```javascript
function getComputedStyle(element, prop) {
   if (element.currentStyle) {
        return element.currentStyle[prop];
    } else if (window.getComputedStyle && window.getComputedStyle(element, null)) {
        return window.getComputedStyle(element, null).getPropertyValue(prop);
    } else {
        return element.style[prop];
    }
}

**Comment by marcj** [comment]
Would you like to send a pull request?

**Comment by shapeshifta78** [comment]
did that ;)
