### ISSUE TITLE
Multiple elements?

### ISSUE THREAD

**Issue by norfali** [marcj/css-element-queries#150]
Was testing element-queries when I spotted something weird - unless it is a codepen issue, the element-queries doesn't seem to get applied to multiple elements. I have done a small pen - http://codepen.io/norfali/pen/YNBMOm

Here, we can see that foo-title works but foo-thing and foo-th do not work.

Is this a bug or something I missed...?

**Comment by acusti** [comment]
They’re all working for me when I view your demo:

<img width="1439" alt="screen shot 2017-02-25 at 9 45 39 am" src="https://cloud.githubusercontent.com/assets/517889/23333369/45fb7b70-fb3f-11e6-8ccd-b1ded8f56d46.png">

**Comment by marcj** [comment]
Works here as well. in which browser didn't it work?

**Comment by enventa** [comment]
I also get that weird behavior **norfali** spotted. But it is not related with multiple elements.

Making window resize (with responsive design mode), CSS styles do not change. BUT, if you go and change anything on the HTML markup (add just an space after any line), then it starts to work... It must be something with CodePen...

Testing with Firefox 52.0.2.

**Comment by marcj** [comment]
Closing for now. Please reproduce in the upcoming 1.0.0 version and reopen if necessary.
