### ISSUE TITLE
Remove IE7 / IE8 support

### ISSUE THREAD

**Issue by kaljak** [marcj/css-element-queries#157]
Lots of libraries have already dropped the support of IE7 / IE8 and I think so should do this library.

e.g. "attachEvent" or "domLoaded" function

**Comment by akomm** [comment]
Many even dropped 9 & 10 support.

**Comment by kobeaerts** [comment]
Yeah, we're 2017. Time to drop everything below IE11 🎉

**Comment by marcj** [comment]
well, no need for that since IE is actually on of the browser that supports this native :D

**Comment by kaljak** [comment]
To make it more explicit I created this commit: https://github.com/kaljak/css-element-queries/commit/bc7d5608aeb1c0afc8135a05e2dfc0400bbd44f7

All workarounds, that are only needed for IE8 and maybe Firefox < 3.6 are removed. I will make a pull request if you know now what I mean :)
