### ISSUE TITLE
External stylesheets won't work in Firefox: "SecurityError: The operation is insecure."

### ISSUE THREAD

**Issue by eroux** [marcj/css-element-queries#16]
Taking the same title as https://github.com/tysonmatanich/elementQuery/issues/10 Apparently there is one solution described here which is to use the prod branch of elementQuery and to specify the css files to parse. But in order to get the good configuration, the Readme asks to use `console.log(JSON.stringify(elementQuery.selectors()));` which doesn't work with ElementQueries. Is there a workaround?

Thank you,

**Comment by marcj** [comment]
The error won't be thrown anymore, but there is no support for loading resources from thirdparty domains, so I'm closing this.
