### ISSUE TITLE
Support for multiple-condition queries

### ISSUE THREAD

**Issue by atsepkov** [marcj/css-element-queries#161]
The article describing element queries (https://www.smashingmagazine.com/2013/06/media-queries-are-not-the-answer-element-query-polyfill/) mentions a multi-condition query, for example:

    .element[min-width~="200px"][min-height~="400px"] .child {
        ...
    }

Is it possible to add support for this? I often find this condition useful for making best use of real estate in an element when it can be resized both horizontally and vertically.

**Comment by marcj** [comment]
Doesn't this work already?

**Comment by atsepkov** [comment]
I'm sorry, I thought it wasn't but looks like the error was on my end. I had a typo in my queries, which I just noticed, then double-checked with the docs and after not seeing an example checked the code. The regex I saw (https://github.com/marcj/css-element-queries/blob/master/src/ElementQueries.js#L326) looked like it only matched a single attribute but now with another test I'm seeing that it does work as expected.
