### ISSUE TITLE
minor optimization

### ISSUE THREAD

**Issue by FranckFreiburger** [marcj/css-element-queries#164]
At [ResizeSensor.js:140](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js#L140), maybe the following test
```
getComputedStyle(element, 'position') == 'static'
```
could be replaced by :
```
element.resizeSensor.offsetParent !== element
```

then remove getComputedStyle()

**Comment by marcj** [comment]
Are you thinking about performance gains or why do you want to get rid of getComputedStyle?

**Comment by FranckFreiburger** [comment]
Both, performance gains then get rid of getComputedStyle() (since it is not used any more).

**Comment by marcj** [comment]
Alrighty, would you want to create a pull request?

**Comment by FranckFreiburger** [comment]
ok
