### ISSUE TITLE
Add support for webpack externals (UMD)

### ISSUE THREAD

**Issue by Toilal** [marcj/css-element-queries#166]
Actually this library supports webpack partially. It works when bundling css-element-queries into the application at build time, but it doesn't work when resolving css-element-queries at runtime using [externals](https://webpack.js.org/configuration/externals/).

Entrypoint should declare an [UMD loading pattern](https://github.com/umdjs/umd/blob/master/templates/returnExports.js) to avoid such issues.

**Comment by marcj** [comment]
Can you send a pull request?

**Comment by marcj** [comment]
Closing due missing feedback.
