### ISSUE TITLE
Maybe it's time for a new release

### ISSUE THREAD

**Issue by hpvd** [marcj/css-element-queries#173]
Maybe it's time for a new release, just to bring fixes and optimizations to public...

![2017-06-12_14h53_47](https://user-images.githubusercontent.com/5681880/27034717-0f8b11ce-4f7f-11e7-8005-563227042f6e.png)

**Comment by Michaelmcd729** [comment]
I tested the tip of the Master branch on IE8 and IE9, and found the following issues.

IE8:
- The resize bar does not appear and attempting to resize the containers does not work.
- The buttons for Responsive Animation and the Performance Demo do not do anything when pressed.

IE9:
- The resolution listed in the Responsive Image container does not change when the size thresholds are reached.
- The Responsive Layout does not change color and the 1/2 boxes can end up having different sizes. (See screenshot)
- The ResizeSensor Demo display stays at '0'.
- The Performance Demo only creates the tags (#0-#X, See screenshot)

These tests were run on my Intel laptop running windows 10 through VirtualBox running windows 7.
I also tested the following, which worked just fine.

On my Intel laptop running windows 10:
- Chrome 58
- Chrome 59
- IE 11
- Firefox 47
- Firefox 53
- Firefox 54

On VirtualBox:
- IE10

On BrowserStack:
- Android Galaxy Note 4 (Chrome, Firefox, and Samsung Browser)
- iPhone 6S (Chrome, Firefox, and Safari)
- iPhone 5 (Safari)
- iPad Air (Safari)
- Windows Phone Lumia 930 (Internet Explorer 11)
- Edge 14 & 15 (Windows 10)
- IE 11 (Windows 8.1)
- IE 11 (Windows 7)
- Firefox 54 & 53 (Windows 8.1)
- Firefox 54 & 53 (Windows 7)
- Chrome 59 (Windows 8.1)
- Chrome 59 (Windows 7)

![ie9-win7-multibox](https://user-images.githubusercontent.com/29552350/27397117-4b0ee9f4-5683-11e7-94fd-136ba0c0ac5f.jpg)
![ie9-performance demo](https://user-images.githubusercontent.com/29552350/27397118-4b10f212-5683-11e7-8916-931e13b9f49d.jpg)

**Comment by privard** [comment]
Thanks @Michaelmcd729! @marcj I can vouch for him. I helped him with the tests.

**Comment by marcj** [comment]
oh well, I guess we need to address these bugs first before we can release :(

**Comment by privard** [comment]
Or we can create a new major build that drops support for IE8 and IE9? What are the stats these days. Last I supported these browsers was at least 3 years ago.

**Comment by marcj** [comment]
Yeah we could basically do that, but to be honest IE6-IE9 is the browser that is the easiest to support when we'd not use the resize hack, but just the regular IE-Only "onresize" event (which is already element based).  However, I guess most of the bugs stated above is related to some Demo code only. Should be easy to fix I guess.

**Comment by hpvd** [comment]
having a new major build which drops support of older IEs may be a good looking quickfix.
Imho there are at least 4 points to be considered:
- doing this, on should ensure that the latest version of "old" major build works flawlessly with the older IEs (otherwise their is no real difference from users POV: both major builds doesn't work right with older IEs)
- not supporting something should be done with a gently fail safe mode, so that there nothing looks broken and main functions are still accessible
- there are still many people using or having to use older versions because you can not always change the software used on your own (big companys..) e.g. in B2B business it's still very important to take care for this
- it's a good additional USP for choosing marcj/css-element-queries (yes, I know there are other bigger ones like speed..)

**Comment by marcj** [comment]
@hpvd Your 4 points are pro "remove IE support"?

**Comment by hpvd** [comment]
@marcj 
no. I'm not a fan of dropping support for older versions of browsers. 
But if one decide to do so (e.g. because it is simply to hard/not possible to support these older browser),
on should really
- think about working on points 1-2 and
- think about/be aware of the things one loose with the decision to drop support (points 3-4)

**Comment by privard** [comment]
To address your first point, are we sure that the problems identified by @Michaelmcd729 are actually regressions? Saw a couple of issues mentioning the resizing not working in various versions of IE in the previous builds.

**Comment by marcj** [comment]
Release 1.0.0 incoming. With this release we only support IE10 and up.
