### ISSUE TITLE
Does not work with SVG tag

### ISSUE THREAD

**Issue by DaanDeMeyer** [marcj/css-element-queries#177]
The ResizeSensor does not seem to work when attached to an <svg> tag. I found #120 but I'm not sure if that applied to svg elements such as <g> and <line> or also to the <svg> elements.

No error is thrown when a resizeObserver is attached to a <svg> tag, the callback function just isn't triggered when the <svg> tag is resized. Wrapping the <svg> in a <div> and attaching the ResizeSensor to that <div> does work.

**Comment by marcj** [comment]
Yeah that is because elements in SVG can not contain a scrollbar AFAIK.

**Comment by DaanDeMeyer** [comment]
Ok, I'll use the workaround with the div then
