### ISSUE TITLE
Only adds position relative, does not add min-width

### ISSUE THREAD

**Issue by jordan-webdev** [marcj/css-element-queries#178]
I'm trying to implement this into my WordPress theme. I've imported the files to the head.

```
wp_enqueue_script('jwd-resize-sensor-js', get_template_directory_uri() . '/inc/element_queries/ResizeSensor.js');
    wp_enqueue_script('jwd-element-queries-js', get_template_directory_uri() . '/inc/element_queries/ElementQueries.js');
```

CSS
`.showcase__header[min-width~="400px"] {
  display: none;
}`

However, the header is still visible. The min-width attribute is not being applied, but "positon: relative" is being added as an inline style.

**Comment by marcj** [comment]
Have you tried `.showcaseheader[min-width~="400px"] { display: none; }`, maybe its a regex issue.

**Comment by jordan-webdev** [comment]
Just tried, but no luck. Position: relative; added, but nothing else. No console errors.

I'm wondering if it has to do with the way WordPress enqueues scripts.

**Comment by marcj** [comment]
then we need a working demo and browser version to reproduce it. Maybe jsfiddle or something

**Comment by marcj** [comment]
Closing due missing feedback. Not possible to fix it without being able to reproduce it.
