### ISSUE TITLE
ResizeSensor is not recognizing changes to div in Chrome...

### ISSUE THREAD

**Issue by venkatpolisetti** [marcj/css-element-queries#186]
I am using Chrome: 60.0.3112.101 (Official Build) (64-bit) on windows 7 and it is not registering resize events for the Chrome browser. It works well in IE 11, though.

Here is the JS code:

``
new ResizeSensor(glc$('table[id$=glc_dynamic_table]'), function() {
	console.log('ResizeSensor fired for: glc_dynamic_table');
});
``
Any ideas?

**Comment by venkatpolisetti** [comment]
I found out that when I am on 24 inch monitor, it is firing events but where on a 13 inch laptop the same page does not produce the events.

**Comment by marcj** [comment]
does the demo site work for you? http://marcj.github.io/css-element-queries/

**Comment by wizzbangwa** [comment]
No, doesn't work in chrome.  Look at the last example with the developer tools open in chrome.  Nothing is added to the console.
