### ISSUE TITLE
`ResizeSensor` not works under IE?

### ISSUE THREAD

**Issue by aleen42** [marcj/css-element-queries#188]
I have recently used ResizeSensor for detecting changment of size for an element, but it seems that the event has not been triggered yet under ID when I change the size of `$wrapper`, and does it support IE?

![image](https://user-images.githubusercontent.com/9573300/29624524-e25881da-885b-11e7-8eee-3817b832fd7a.png)

**Comment by aleen42** [comment]
I have tested that it only supports above IE10, while IE9 and IE8 is not.

**Comment by marcj** [comment]
Well, does the demo site works in your IE9/8?

**Comment by aleen42** [comment]
I check it later

**Comment by aleen42** [comment]
![image](https://user-images.githubusercontent.com/9573300/29663709-10aa966a-88ff-11e7-904f-e2abeac5ba4b.png)

It seems that I cannot use the demo

**Comment by aleen42** [comment]
![image](https://user-images.githubusercontent.com/9573300/29663732-2a5ab0c2-88ff-11e7-8320-fdcef17f5878.png)

Please check your script first.

**Comment by aleen42** [comment]
So is there any result?

**Comment by marcj** [comment]
No

**Comment by aleen42** [comment]
@marcj Ok, I am waiting foy your fixing.

**Comment by marcj** [comment]
Should be fixed, will be part of the next version 1.0.0 in the next hours. We support only IE 10 and plus now.
