### ISSUE TITLE
Support for Web-Component?

### ISSUE THREAD

**Issue by yairopro** [marcj/css-element-queries#191]
Hi =)

**Does ResizeSensor support Web-Component?**
If yes, maybe there's something wrong with my [demo](https://plnkr.co/edit/vqMLOwR9xM2epanrVWtl?p=preview). The Web-Component I made (using Google's Polymer 2.0 library) should log `resized` when it's resized, but it doesn't log anything.

**Comment by alijaya** [comment]
+1

**Comment by yairopro** [comment]
@alijaya I'm using [pelotoncycle/resize-observer](https://github.com/pelotoncycle/resize-observer). It's currently the only lib I've found which works. Actually it works great. I haven't got any problem with it.

**Comment by alijaya** [comment]
thanks for the sugestion :D
