### ISSUE TITLE
ResizeSensor throws error when called

### ISSUE THREAD

**Issue by om-nishu-trantor** [marcj/css-element-queries#192]
I simply included this script in my html file, and then tried to call 
```javascript
new ResizeSensor(jQuery('#my-container'), function(){ 
    console.log('content dimension changed');
});
``` 

It throws 
```javascript
Uncaught TypeError: ResizeSensor is not a constructor
```

I am sure there is another way to initialise/call the constructor. Can someone put that out here, should be updated in docs/demo as well

**Comment by marcj** [comment]
Because you haven't included the ResizeSensor.js in your html.
