### ISSUE TITLE
ResizeSensor not functioning on IE8 after changes made since 0.0.2

### ISSUE THREAD

**Issue by vivid-inc** [marcj/css-element-queries#20]
I confirmed that with tag 0.0.2, IE8 (using modern.IE) functions correctly and IE11 (also modern.IE) fails, as stated. With the same browser setup coupled with the software from master @ 0975de58, IE11 appears to function correctly but IE8 no longer functions. Confirmed the above in my test bench and using the last demo (demo #5?) in test\index.html. Chrome, Firefox, & Safari operate correctly with both versions. I didn't try IE9 or IE10.

The commit logs indicate that support for IE11 was added, and inspecting the source code reveals that ResizeSensor.js in master @ 0975de58 was largely rewritten since 0.0.2.

BTW, I appreciate that the nature of the work you are doing here is difficult… Ganbatte!

**Comment by o-nix** [comment]
Huh, so it doesn't actually work now?

**Comment by marcj** [comment]
@vivid-inc does @ajmueller's fix resolves your issue?

**Comment by vivid-inc** [comment]
@marcj Don't have an answer for you, sorry. We had to move past this issue, so for IE8 we set a listener for jquery's resize() event on the window. Sub-optimal perhaps, but still effective.

**Comment by erikwinlof** [comment]
I found a similar issue when testing IE9 (using virtual box and an image from modern.ie with Windows 8 and IE9) where IE9 never got the "scroll" events. It worked fine for IE11though. 

After some digging I found that similar libraries are using the IE proprietary "resize" event on the element when running IE. So I locally patched ResizeSensor.js v0.3.0 to use the "error" event instead of "scroll" (when running IE9) and it all worked fine.

**Comment by hambyje** [comment]
If I am understanding correctly the only change you made in ResizeSensor.js was the following for IE9
addEvent(expand, 'error', onScroll);

**Comment by erikwinlof** [comment]
@hambyje See below. Once its not necessary to support ie9 anymore it can be removed since it works fine for IE10 & IE11.

```
if (isIELessThan10) {
    // Internet explorer 9 does not listen to scroll events (but fortunately proprietary "onresize" events)
    addEvent(expand, 'resize', onScroll);
    addEvent(shrink, 'resize', onScroll);
}
else {
    addEvent(expand, 'scroll', onScroll);
    addEvent(shrink, 'scroll', onScroll);
}
```

**Comment by hambyje** [comment]
Thanks

**Comment by marcj** [comment]
Dropped IE9 and lower support.
