### ISSUE TITLE
ResizeSensor bug when getting element position property

### ISSUE THREAD

**Issue by artemnikotin** [marcj/css-element-queries#207]
Seems you have problem (version 1.0.0) on line 147, when trying to get element position, but got position priority
```javascript
var position = window.getComputedStyle(element).getPropertyPriority('position');
if ('absolute' !== position && 'relative' !== position && 'fixed' !== position) {
    element.style.position = 'relative';
}
```

**Comment by marcj** [comment]
What do you mean? "position priority"? What error do you get?

**Comment by artemnikotin** [comment]
Hi, @marcj 
In my project, ResizeSensor overwrite 'position' property to "relative", even if I set it via css to "absolute".

[getPropertyPriority()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyPriority) method returns the priority of the property, e.g. "important" or empty string, but in described code we are waiting for the property value (we produce comparisons with 'position' values). We can use [getPropertyValue()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue) for it. So line 147 could be replaced on:
```javascript
var position = window.getComputedStyle(element).getPropertyValue('position');
```
What do you think?

**Comment by marcj** [comment]
Oh you're right, a stupid typo. Would you like to provide a PR?

**Comment by marcj** [comment]
fixed
