### ISSUE TITLE
ResizeSensor - Make current dimensions readable

### ISSUE THREAD

**Issue by movedoa** [marcj/css-element-queries#209]
It would be great if there was a way to read the current dimensions of the resize sensor. (I guess it should be known?)

At the moment i need to read width and height again in the event, which costs time.

**Comment by marcj** [comment]
Sure, please provide a PR. Should be a easy fix 👍

**Comment by movedoa** [comment]
Will you merge #208 any time soon? I already use this version since it just works better (at least for me)
I would base my pr on that

**Comment by marcj** [comment]
Has been added in https://github.com/marcj/css-element-queries/pull/213
