### ISSUE TITLE
ResizeObserver in Chrome 64

### ISSUE THREAD

**Issue by bbeckford** [marcj/css-element-queries#210]
Hi all,

Would it be possible to integrate the new native ResizeObserver listener released in Chrome 64?

Browser support is very limited at this stage (https://caniuse.com/#search=ResizeObserver) but it looks like a potentially more efficient way of achieving what ResizeSensor.js tries to do.

https://developers.google.com/web/updates/2016/10/resizeobserver
(Now live - https://developers.google.com/web/updates/2018/01/nic64)

If I get a moment next month I may try to add it myself where `typeof ResizeObserver != "undefined"`, but I thought I'd let you guys know about it if it hasn't already been discussed :)

**Comment by marcj** [comment]
I'd not go that way as it would make stuff more complicated than it should be. We should think about integrating ResizeObserver as soon as it has support in all major browsers.

**Comment by movedoa** [comment]
i already have a working implementation of this in resizesensor, its just a few lines of code so no bloat or complicated stuff here, just much better performance in chrome

I will try to create a pr for this in the next few days, except you are strictly against this idea, but i see no real reason not to do this

**Comment by bbeckford** [comment]
Yeah I'm not sure why you wouldn't include it on the undefined check, it will just start working as browsers add support. Even when all browsers implement it you'll still need the fallback for legacy.

**Comment by bbeckford** [comment]
Nice! Thanks all :D
