### ISSUE TITLE
Unable to parse distant css files (S3 css files)

### ISSUE THREAD

**Issue by rawpixel-vincent** [marcj/css-element-queries#211]
The css parsing doesn't works if the css that contain media queries are stored on a distant server (we tested with Amazon S3).

Not sure how to solve this or if it can be solved. 

Just thought it would be good to report it for now.

**Comment by marcj** [comment]
This is not supported as the browser has no access to resources from a cross domain. Either use the same domain to deliver your content and set cross domain headers.
