### ISSUE TITLE
Broken EQs in some browsers

### ISSUE THREAD

**Issue by Gywem** [marcj/css-element-queries#215]
The newest version 1.0.1 has introduced errors on resolve multiple EQs on the same element. I have seen it working fine in Safari (11.0.3) though, but not in Chrome (64) or Firefox (49.0.1)

The effect can be seen [on the example page](http://marcj.github.io/css-element-queries/) actually. If you visit the "Responsive Text" example, and you drag the gray line, you will see that no EQs are applied. I've seen this happening on my project, the thing there is that only one EQs defined for the same element is applied.

**Comment by marcj** [comment]
Interesting newest Chrome and Firefox broke, but I don't know why at the moment.

**Comment by AndrewBogdanovTSS** [comment]
Same behavior for me.
Chrome 64
FF 58

**Comment by marcj** [comment]
My master version works perfectly fine in those browsers, I guess the example page just has an old version.

**Comment by marcj** [comment]
I released 1.0.2 and example page works again. If you still have issues please let me know so I can reopen.

**Comment by AndrewBogdanovTSS** [comment]
What was the problem?

**Comment by 7iomka** [comment]
@marcj, You updated version to the latest on demo site? I tested demo site with ipad air with ios 8.3 (on browserstack.com) and example with text not working!(
