### ISSUE TITLE
TYPO at findElementQueriesElements - please, release version

### ISSUE THREAD

**Issue by el-fuego** [marcj/css-element-queries#216]
Need to use `findElementQueriesElements` to make css reading once, but adding elements in runtime.

`for (var selector in allQueries) if (allQueries.hasOwnProperty(mode)) {`
`mode` shold be replaced with `selector`

It is already fixed in master, so, please, release new version

**Comment by marcj** [comment]
> It is already fixed in master, so, please, release new version

I don't see it fixed.

**Comment by marcj** [comment]
I added it now and released 1.0.2
