### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': param 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by rejhgadellaa** [marcj/css-element-queries#219]
Hi there,

I'm trying to use your library but I'm getting an error:

> Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
>     at HTMLBodyElement.<anonymous> (ElementQueries.min.js:421)

This is line 421:

`var sensorStyles = window.getComputedStyle(element.resizeSensor, null);`

So.. element.resizeSensor is not an element. I just checked and it's actually undefined :(

Any clue what's wrong?

**Comment by mhlavacek** [comment]
I'm getting the same error.

**Comment by mhlavacek** [comment]
I was able to at least get a workaround going while the issue gets fixed.  Update line 421 in the ElementQueries.js file to be the following...

`var sensorStyles = window.getComputedStyle(element.resizeSensor || element, null);`

@rejhgadellaa

**Comment by marcj** [comment]
This issue is coming from the fact that in the newest master version we use ResizeObserver in Chrome where `element.resizeSensor` is then really undefined. See #213 by @movedoa

Please use 1.0.2 instead of the master version.

**Comment by rejhgadellaa** [comment]
Awesome thanks! 🎈

**Comment by enventa** [comment]
@marcj 
I'm afraid using version 1.0.2 doesn't fix this issue. At least, on my installation doesn't work, the problem appears using both, 1.0.2 and master version.

**Comment by marcj** [comment]
This should be fixed in the latest version. Please try again and give feedback

**Comment by wrightdaniel2017** [comment]
still getting issue in 2022!
