### ISSUE TITLE
TypeError: window.getComputedStyle(...) is null

### ISSUE THREAD

**Issue by JuusoPalander** [marcj/css-element-queries#222]
## Versions
**css-element-queries version:** 1.0.2
**Browser:** Firefox 59.0.1 (64-bit)
**OS:** MacOS High Sierra 10.13.3

## Issue - ResizeSensor.js:150
```javascript
var position = window.getComputedStyle(element).getPropertyValue('position');
```
Here `window.getComputedStyle(element)` can return `null` at least on Firefox, and then the subsequent call to `.getPropertyValue('position')` will throw an error.

## Fix
```javascript
var computedStyle = window.getComputedStyle(element);
var position = computedStyle ? computedStyle.getPropertyValue('position') : null;
```

## Related Firefox bug report
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

**Comment by marcj** [comment]
Can you provide a pull request please?

**Comment by JuusoPalander** [comment]
Don't have rights to open it directly. Do you want me to fork the repo and do it that way?
