### ISSUE TITLE
if the parent node is not displayed when it is initialized, the event of the child node cannot be triggered when the parent change is displayed.

### ISSUE THREAD

**Issue by zsedcbm** [marcj/css-element-queries#228]
I used [Vue.resize](https://github.com/David-Desmaisons/Vue.resize/), it used ResizeSensor.js

child component used v-resize

when parent used v-show, the dom with v-show is "display:none", then child resize event is not work

when parent used v-if, then child resize event is work,

![4](https://user-images.githubusercontent.com/5986396/40224209-0b73028c-5ab8-11e8-81e4-a2d83c743f0d.gif)

[https://codepen.io/zsedcbm/pen/erQomg](https://codepen.io/zsedcbm/pen/erQomg)

**Comment by zsedcbm** [comment]
I simplified the example.

If the child node is displayed at the time of initialization, then the child node can trigger the event normally.

![normal](https://user-images.githubusercontent.com/5986396/40288196-92d9e6c2-5ce4-11e8-8b1b-326db01c2a7a.gif)

However, if the child node is not displayed when it is initialized, the event of the grandchild node cannot be triggered when the later change is displayed.

![error](https://user-images.githubusercontent.com/5986396/40288315-307a60a0-5ce5-11e8-8cb3-ef88ede8217e.gif)

[https://codepen.io/zsedcbm/pen/VxgMJL](https://codepen.io/zsedcbm/pen/VxgMJL)

**Comment by marcj** [comment]
This should be fixed in current version. Can you retry?

**Comment by zsedcbm** [comment]
good job, it worked

**Comment by blemaire** [comment]
This should ideally be fixed in this repository, otherwise every application that uses a similar system as v-show in Vue.resize has to implement a similar method. Per instance we use angularJs and we have the same issue when we use ng-if. 
Thanks

**Comment by marcj** [comment]
@blemaire have you tried the current version? If it doesn't work, please prepare me some reproduction code, on jsfiddle or somewhere.
