### ISSUE TITLE
import of ResizeSensor in angular

### ISSUE THREAD

**Issue by khan990** [marcj/css-element-queries#230]
Importing of ResizeSensor in angular causes the following error:
> ERROR TypeError: ResizeSensor is not a constructor

https://stackblitz.com/edit/css-element-queries-d

It somehow magically works only in this project:
https://stackblitz.com/edit/css-element-queries-d-resize-sensor

Replicating the same in local machine and elsewhere returns the error that I mentioned earlier.

**Comment by khan990** [comment]
I unnecessarily complication the import. Here is the corrected version.
https://stackblitz.com/edit/css-element-queries-d-corrected

import should be: 
`import { ElementQueries, ResizeSensor } from 'css-element-queries' ;`
instead of 
```
import * as ElementQueries from 'css-element-queries/src/ElementQueries';
import * as ResizeSensor from 'css-element-queries/src/ResizeSensor';
```

**Comment by koscik** [comment]
> I unnecessarily complicated the import. Here is the corrected version.
> https://stackblitz.com/edit/css-element-queries-d-corrected
> 
> import should be:
> `import { ElementQueries, ResizeSensor } from 'css-element-queries' ;`
> instead of
> 
> ```
> import * as ElementQueries from 'css-element-queries/src/ElementQueries';
> import * as ResizeSensor from 'css-element-queries/src/ResizeSensor';
> ```

Sadly, this way of importing is no longer working for me. I need to use 

> import * as ResizeSensor from 'css-element-queries/src/ResizeSensor';

and than like this:

> this.resizeSensor = new ResizeSensor.default(

anyone know why is that a case?

**Comment by davidenke** [comment]
> > I unnecessarily complicated the import. Here is the corrected version.
> > https://stackblitz.com/edit/css-element-queries-d-corrected
> > import should be:
> > `import { ElementQueries, ResizeSensor } from 'css-element-queries' ;`
> > instead of
> > ```
> > import * as ElementQueries from 'css-element-queries/src/ElementQueries';
> > import * as ResizeSensor from 'css-element-queries/src/ResizeSensor';
> > ```
> 
> Sadly, this way of importing is no longer working for me. I need to use
> 
> > import * as ResizeSensor from 'css-element-queries/src/ResizeSensor';
> 
> and than like this:
> 
> > this.resizeSensor = new ResizeSensor.default(
> 
> anyone know why is that a case?

@koscik Have you tried `import { ElementQueries, ResizeSensor } from 'css-element-queries';`?
Works fine for me on Angular 7.1, and looks good in the [StackBlitz on Angular 6](https://stackblitz.com/edit/css-element-queries-d-corrected)...
