### ISSUE TITLE
Add a configurable delay?

### ISSUE THREAD

**Issue by keul** [marcj/css-element-queries#231]
I'm fallen in a issue similar to #223. In my case the issue is generated by a plotly.js graph inside the monitored container on some specific window sizes near to the point where scrollbars are displayed hidden.

What I guess is happening:

* I resize the window
* css-element-queries resize the container
* plotly.js react to the resize event and repaint the graph with a different size, which change the container size
* css-element-queries recalc on the container
* plotly again...

So here I'm in an loop which never ends. I'm guessing if adding a configurable delay can be an option here.

**Comment by marcj** [comment]
The question is, why does plotly.js always changes its size when rendering?

**Comment by keul** [comment]
It's probably a good question, unluckily I don't have much domain on the plotly part, I don't know why there's a delay and render there.
