### ISSUE TITLE
What is correct way to integrate ElementQueries to React using Webpack,Typescript and SASS?

### ISSUE THREAD

**Issue by bonniss** [marcj/css-element-queries#242]
Hi guys, I'm trying to integrate the library to my React project generated by JHipster. 
I add cdn version of the library at : https://cdnjs.com/libraries/css-element-queries;
Then i add a script at the end of body section of index.html:
```
<script>
        window.addEventListener('DOMContentLoaded', function(event){
            ElementQueries.listen();
        });        
</script>
```
I have checked in the console, ElementQueries has loaded correctly;
But when i change SASS file like the 1st example of the page: http://marcj.github.io/css-element-queries/
, nothing happens;
Since I'm quite fresh to React and Typescript, any help would be appreciated!

**Comment by marcj** [comment]
Can you setup a jsfiddle somewhere to reproduce it?
