### ISSUE TITLE
Seo and chrome 41

### ISSUE THREAD

**Issue by andrey11231990** [marcj/css-element-queries#244]
Hi
I'm trying to check how google will index my page. As I had read, google uses Chrome 41 to index js on site. When I'm trying to open my site in Chrome 41.0.2272.89 (64-bit) on macOs I will receive exception in file ElementQueries.js. The exception will be thrown in 'init' function, because there is something wrong comes in as a parameter of event-handler (e.target === undefined).

Required version of chrome you can find here (https://google-chrome.en.uptodown.com/mac/old)

Also, for testing purpose I've created simple empty project and it's located here (https://github.com/andrey11231990/testcsseq). It is empty create-react-app, in which I've added the library and call 'EQ.ElementQueries.init();' in setTimeout. When animation will start - you'll see the exception in console (Uncaught TypeError: Cannot read property 'indexOf' of null).

Is there anything that you can offer to fix the problem ?

**Comment by marcj** [comment]
Since May 2019 Googles bot runs on newest Chromium version, so this should be fixed.
