### ISSUE TITLE
ResizeSensor stops working after target element's position in DOM tree changes

### ISSUE THREAD

**Issue by martynasma** [marcj/css-element-queries#246]
The ResizeSensor works fine until target element is moved to other parent, say with an `appendChild()` method.

Example:
https://codepen.io/team/amcharts/pen/3411d5d33bf8af44ba5183ed0d33b27c

Resize is registered fine until parent of the test container changes.

Would it be possible to update ResizeSensor to register such change? Or, perhaps, there's some method that would allow "re-initializing" sensor after the move?

**Comment by marcj** [comment]
Is fixed in newest version. Please try and send feedback if possible.

**Comment by martynasma** [comment]
Works beautifully. Thanks!
