### ISSUE TITLE
Browserify, publish on NPM

### ISSUE THREAD

**Issue by sverrejoh** [marcj/css-element-queries#25]
Hi,

The package isn't browserify-able, or on npmjs.org.

Is there any reason for this that I'm missing?

**Comment by Schubidu** [comment]
@slorber maybe it will help you to install the latest version of this repository easily from [Github](https://docs.npmjs.com/cli/install#description).

    npm i marcj/css-element-queries#v0.2.1

After you done it, include the JS-files in your script.

    require('css-element-queries/src/ElementQueries');
    require('css-element-queries/src/ResizeSensor');

This solution will work with node 0.12 and npm 2.11

**Comment by Schubidu** [comment]
@slorber you will find it on [npm](https://www.npmjs.com/package/css-element-queries)
