### ISSUE TITLE
How to use or remove the console message "CssElementQueries: unable to parse local css files," ? 

### ISSUE THREAD

**Issue by stephyswe** [marcj/css-element-queries#260]
Hi, 

Your JS lib is working nicely. 

But I don't really understand what unable to parse local css is? Can author or someone please help me get rid of the console.log message or elaborate what it means ?

**Comment by marcj** [comment]
As in the readme stated

> Local stylesheets do not work (using file:// protocol).

Its due to security concerns. Reading css files loaded from `file://` urls violates a [Cross-Origin Resource Sharing (CORS) policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and thus will never be supported.
