### ISSUE TITLE
Multiple instances ?

### ISSUE THREAD

**Issue by sparqueur** [marcj/css-element-queries#27]
In the document is written :

After including ElementQueries.js the class attaches the `init` method to `load` event of the page, so it get initialised after all CSS files have been loaded.

Class ElementQueries()
    -> init() // Scans all css rules and do the magic.
    -> static update() //rescans the dom for newly inserted elements.

As written, I expect it to instanciate itsale and be able to call static methods.

Unfortunatly, when I try to do a ElementQueries.update() (or ElementQuery.update() as in issue #9) it doesn't work (undefined is not a function)
The only I found to make is work is as bellow :
var elementQueries =  new ElementQueries();
elementQueries.update();

Why do I have to instanciate it manually ? And when do I exactly need to do it ?

Thanks in advance

**Comment by marcj** [comment]
Yeah, this bug with the static update method has been fixed now.
