### ISSUE TITLE
ResizeSensor doesn't call an update when div's value is changed

### ISSUE THREAD

**Issue by MikeYermolayev** [marcj/css-element-queries#270]
Hi there,

So, I experience the next problem:
I attach ResizeSensor to a span which can change it's width and it's value during the time.
When I change width of span - everything works as expected
But when I change span's value and it's width got changed as a side effect - ResizeSensor doesn't notify me.

Is it expected behavior?

Thanks in advance

"css-element-queries": "1.1.1"
MacOs 10.14.4 Mojave
Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by marcj** [comment]
Please provide an working example using stackblitz/jsfiddle/etc

**Comment by MikeYermolayev** [comment]
Sorry, looks like found an issue.

I use react and after state update it just removes ResizeSensor's nodes.

Closing for now
