### ISSUE TITLE
Can't use display:none

### ISSUE THREAD

**Issue by flivni** [marcj/css-element-queries#274]
I want to conditionally display a `div` based on its width.

I'd like to do something like this:
```
.mydiv[min-width~="300px"] {
    display: none;
}
```
But it doesn't work.

I thought at first this was a duplicate of #46. But, it looks like #46 has been fixed. And perhaps my situation is a bit different.
 
Demonstration in [this fiddle](https://jsfiddle.net/flivni/1t4bsn8L/28/).

**Comment by LorenzGardner** [comment]
It doens't seem to redo the layout to make room for the 2nd div, as a workaround if you change the example2 css to bi "visibility: collapse;" it works as you expect.

**Comment by marcj** [comment]
That's not logically resolvable. If you hide an element (like in you did) the element loses its dimensions and will never receive an resize event anymore. Without dimensions it's impossible to detect whether the element got bigger or smaller to check if a rule matches. So, what you should do is to put the rule on a parent that is always visible. https://jsfiddle.net/21ekLn5y/2/

**Comment by flivni** [comment]
Thanks. Your workaround and explanation makes sense. I think my scenario might be a common case -- perhaps it should be documented?
