### ISSUE TITLE
Can't create a new ResizeSensor without a callback

### ISSUE THREAD

**Issue by andi-b** [marcj/css-element-queries#275]
I can't create a new Resize sensor without passing through an empty function:

new ResizeSensor($(this), function () { });

The code assumes that a function will always be passed through and tries to call it.

**Comment by marcj** [comment]
Why would you want to create a sensor without using its emitted values?

**Comment by andi-b** [comment]
You may want to dynamically add a new element to the dom and add the sensor to it so that it works with the conditional css, but not have a function to call when the new element resizes.

**Comment by marcj** [comment]
You should call `ElementQueries.init()` when you dynamically added new elements. However, usually the animation-hook automatically finds those elements.

**Comment by andi-b** [comment]
Of course that makes total sense. Not sure animation hook did, but will keep that in mind. Thanks!
