### ISSUE TITLE
Documentation missing for the difference between =, ~=, ^=

### ISSUE THREAD

**Issue by mimshwright** [marcj/css-element-queries#28]
I can't find any documentation about the difference between these three operators.

**Comment by jehoshua02** [comment]
As I predicted, you define the breakpoints with one attribute, then the library analyzes the breakpoints and adds another attribute used to style the element. And the attribute selector is familiar territory to me:

> [attr~=value]
> Represents an element with an attribute name of attr whose value is a whitespace-separated list of words, one of which is exactly "value".

Makes sense. Although a short note in the documentation can't hurt, I don't think how to use the library is undiscoverable, especially with the demo.

**Comment by czebe** [comment]
I agree with @jakob-e, that the only reasonable selector that you can use is  ~=
I was baffled to see mixed order attributes like: max-width="1100px 600px 960px" which make using $= or ^= really pointless. What's the reason for not sorting values?

**Comment by marcj** [comment]
I updated the docs so it uses per default `~=`. A little link and more explanation about that topic is however still on my todo list.
