### ISSUE TITLE
Use-case: watch for child selector

### ISSUE THREAD

**Issue by dragontheory** [marcj/css-element-queries#281]
Is this possible with css-element-queries? 

The class `.loaded` is dynamically loaded into the parent `.results` and triggers the parents sibling `.details` to move left `300px`.
```
.details {     
     position: absolute;     
     right: -300px;
}
.results .loaded {     
     .details {          
          right: 0;     
     }
}
```
Thanks!

**Comment by marcj** [comment]
I don't see any css-element-query rules in your css nor a question related to this library.
