### ISSUE TITLE
Export Size type for typescript

### ISSUE THREAD

**Issue by Maximaximum** [marcj/css-element-queries#292]
This is not a huge issue, but it would be just a little bit more convenient if the library also exported a `Size` type within its typings:

```typescript
export declare interface Size { width: number; height: number; }
export declare type ResizeSensorCallback = (size: Size) => void;
```

instead of just

```typescript
export declare type ResizeSensorCallback = (size: { width: number; height: number; }) => void;
```

The issue is that the type of the `ResizeSensorCallback` argument sometimes has to be specified explicitly, so this minor change would help to avoid retyping `{ width: number; height: number; }` in such cases

**Comment by marcj** [comment]
@Maximaximum feel free to create a PR covering this change. 👍

**Comment by marcj** [comment]
Ops, you already did :D thanks!

**Comment by Maximaximum** [comment]
@marcj thank you. Could you please give a hint regarding when you plan to reslease a new version containing this change?
