### ISSUE TITLE
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by theruler007** [marcj/css-element-queries#295]
I'm using React.js and this is the error I get. Here is my code:

`toggleDiv(id) {
        const elem = document.getElementById(id);
        const display = window.getComputedStyle(elem).getPropertyValue('display');
        if (display === 'none') {
            elem.style.display = 'block';
            return false;
        } else {
            elem.style.display = 'none';
            return true;
        }
    }`

Please tell me how the variable `elem` is not an element.

**Comment by marcj** [comment]
This issue tracker is not for help with your own code.

**Comment by theruler007** [comment]
Oh I'm sorry, I'm new to GitHub.
