### ISSUE TITLE
0.1 does not seem to function in IE9

### ISSUE THREAD

**Issue by tgrenbergj** [marcj/css-element-queries#30]
I was testing cross browser compatibility for the latest version of your plugin, and found that it breaks in IE9.  Even your current demo page does not function.  The same page worked fine in IE10-11, Chrome, and Firefox.  I had multiple people test on multiple machines, so it doesn't seem to be an isolated event.

**Comment by nissoh** [comment]
![image](https://cloud.githubusercontent.com/assets/1410797/5791964/0584eeca-9f05-11e4-982e-de0e6525c811.png)

IE9 Win7

**Comment by mmclau14** [comment]
did anyone ever figure out why the initial callback is not being called? i have tried a variety of event listener functions to no avail.

**Comment by dushyant** [comment]
It's not working for me as well in IE8 + IE9.

**Comment by dushyant** [comment]
Example here: http://marcj.github.io/css-element-queries/ not working in IE8 & IE9.

**Comment by marcj** [comment]
I close this issue as this is referencing v0.1 which is outdated. If you still see issues with newest version please create new issues.
