### ISSUE TITLE
Allow for installation in browsers via a cdn like unpkg or jsdelivr.

### ISSUE THREAD

**Issue by Directory** [marcj/css-element-queries#307]
Just a thought, would be nice, I'm lazy.

**Comment by enventa** [comment]
You mean like this: [https://www.jsdelivr.com/package/npm/css-element-queries](https://www.jsdelivr.com/package/npm/css-element-queries)?

**Comment by Directory** [comment]
oh cool. still. maybe the readme could make that a little more obvious
