### ISSUE TITLE
Provide a detach method

### ISSUE THREAD

**Issue by 3ffy** [marcj/css-element-queries#32]
Hi, 
Your plugin do a great work (ty btw) but it has to add a lot of events / dom elements to works.
So it's pretty hard to "revert" the operation when you want to stop spy on an old element :')... I think it would be really nice to implement it and get a trustable piece of code.

**Comment by marcj** [comment]
It's implemented, in both, ResizeSensor and ElementQueries classes.

**Comment by blq** [comment]
Detach fails if the ResizeSensor was originally attached via jQuery. The 'detach' method needs to use the same sniffing code as the initial attach.
