### ISSUE TITLE
pop-in of styles

### ISSUE THREAD

**Issue by mimshwright** [marcj/css-element-queries#36]
It seems when loading a page with the browser resized to a smaller breakpoint, there is a pop-in when the element queries are processed. 

http://cl.ly/image/1f2h0k0Y2F0M

If there is already a solution to this covered somewhere, please let me know. Thanks!

**Comment by marcj** [comment]
What do you mean? I don't know what you mean with "pop-in when the queries are processed".

**Comment by mimshwright** [comment]
Sorry, I'll explain. When the page loads, the unstyled version of the element (the one without element query styles applied) appears and is replaced a split second later with the element query styles. This is presumably happening after the javascript loads and evaluates the element sizes. So basically, it's a flash of unstyled content (http://en.wikipedia.org/wiki/Flash_of_unstyled_content). 

I'm curious if you've dealt with this issue before.

**Comment by marcj** [comment]
Ah you meant flash of unstyled content. We could start our engine `ondomready` additionally to `onload`, but I guess it's probably not easily fixable as we start our engine on `onload` because we can't detect if all css files have been loaded.

**Comment by mimshwright** [comment]
Hmm. Are there events dispatched when the replacement is finished? Maybe there is some hook you could provide so that people can do their own workaround to avoid the FOUC.

**Comment by marcj** [comment]
I don't think providing an event dispatcher solves the issue with the unstyled flash.

**Comment by wickning1** [comment]
I'm not sure you can ever really eliminate this flash entirely, but one thing we did in a few places was set up media queries that give a good guess of what we expect the final result to look like, then the final pop is less jarring. 

One thing I noticed was that it's a lot less disturbing for an element to start out too small by half than too large by double.
