### ISSUE TITLE
Object doesn't support property or method 'appendChild'

### ISSUE THREAD

**Issue by Yustie** [marcj/css-element-queries#37]
Hi,

I get an instant run time error when using this script. This is the full error msg:

Unhandled exception at line 77, column 13 in http://localhost:60498/Scripts/ResizeSensor.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'appendChild'

It happens on the last line in this piece of code:

`element.resizeSensor.style.cssText = style;
            element.resizeSensor.innerHTML =
                '<div class="resize-sensor-expand" style="' + style + '">' +
                    '<div style="' + styleChild + '"></div>' +
                '</div>' +
                '<div class="resize-sensor-shrink" style="' + style + '">' +
                    '<div style="' + styleChild + ' width: 200%; height: 200%"></div>' +
                '</div>';
            element.appendChild(element.resizeSensor);`

**Comment by marcj** [comment]
Browser, Version, OS, test file?

**Comment by Yustie** [comment]
IE 11, win7 x64, what do ya mean with test file?

**Comment by marcj** [comment]
Does this issue still exist with newest version?

**Comment by Yustie** [comment]
No idea, I don't think I still have this plugin in my project either.
I'm closing it for now.
