### ISSUE TITLE
Can't install as bower package

### ISSUE THREAD

**Issue by Soulskater** [marcj/css-element-queries#38]
Maybe it's not uploaded to bower.herokuapp.com.

**Comment by marcj** [comment]
What does `Can't` mean exactly?

**Comment by Soulskater** [comment]
It throws  Request to https://bower.herokuapp.com/packages/css-element-queries failed with 503 error when i trying to install the package.

**Comment by marcj** [comment]
maybe the bowser server was just under heavy load.

**Comment by Soulskater** [comment]
Okay it seems to work fine right now! Thanks.
