### ISSUE TITLE
Doesn't work with external styles in OSX with Chrome and Safari

### ISSUE THREAD

**Issue by dandaka** [marcj/css-element-queries#40]
css-element-queries doesn't work with external styles in OSX in Chrome 40.0.2214.111 and Safari 8.0.3 (10600.3.18).

Works with Firefox 34.0.5.

All these browsers work fine, when CSS is included inline in STYLE tag.

https://www.dropbox.com/s/hxezwobku2m1uxo/css-elements-query.zip?dl=0

**Comment by marcj** [comment]
It's afaik not possible to read stylesheets loaded via `file:///`. Can you provide please a test uploaded somewhere?

**Comment by dandaka** [comment]
@marcj here is test, which proves, that external files do work correct in all browsers —

http://html.accuraten.com/annarafeeva/eq/index-external.html

I think its good idea to include this as know issue, that in Chrome/Safari this library doesn't work with local stylesheets. With Firefox its working, though.

**Comment by marcj** [comment]
Yes, that's probably a good idea. :)
