### ISSUE TITLE
Element queries init before window.ready?

### ISSUE THREAD

**Issue by dandaka** [marcj/css-element-queries#41]
## Problem

With slow connection and heavy content (lots of images example — http://html.accuraten.com/annarafeeva/public/) we get following results:
1. Initial CSS (without element queries) works almost instantly
2. Element queries waits for all content to load. Which can take 10+ seconds.
3. Element queries applies
4. Final layout is applied (looks like glitch from UX perspective)

I've event added JS files to HEAD, still it waits for all IMGs to load, before parsing CSS / element queries.
## Possible solution

Make this rendering faster. For example:
1. Include element queries inline
2. Ask css-element-queries to parse rules before all content is loaded

Is this possible?

**Comment by marcj** [comment]
Yes, it's the same problem as described in https://github.com/marcj/css-element-queries/issues/36. We could triggerthe element-querie stuff several times: on-domready and on-load.

**Comment by dandaka** [comment]
How can I do this? I have tried ElementQueries.init() and all possible combinations (like ElementQueries.prototype.init) with no result :)

**Comment by marcj** [comment]
that `.init()` is only possible in current master version.

**Comment by dandaka** [comment]
I still can't get, what is the proper syntax to call this init().

ElementQueries.init()
VM244:2 Uncaught TypeError: undefined is not a function

JS from current master version.

**Comment by marcj** [comment]
Just added that ondomready init call to master. `ElementQueries.init` is now also available, so you can call this method whenever you added new elements and when you think its time to call it.

**Comment by dandaka** [comment]
You're the man, Marc! Thank you very much for your work, really appreciated.
