### ISSUE TITLE
Fails to update styles on resize

### ISSUE THREAD

**Issue by lolmaus** [marcj/css-element-queries#45]
Demo: http://emberjs.jsbin.com/pixuva/1/edit?html,css,output

Steps to reproduce:

1. Start with a narrow window. See list items be correctly colored red.
2. Enlarge the window. See list items correctly become transparent.
3. Shrink the window back.

What i expect: list items should become red again.

What actually happens: list items remain transparent.

**Comment by s0ber** [comment]
Works fine for me.

**Comment by chrislachance** [comment]
I'm seeing it too lolmaus. (Chrome 43.0.2357.124 (64-bit), Mac Yosemite)

**Comment by kleinerdrei** [comment]
same problem here (Chrome 44.0.2403.52 beta - 64-bit - Mac Yosemite)

**Comment by annorax** [comment]
Yep, ResizeSensor seems to be somewhat broken. I hooked up ElementQueries to https://github.com/wnr/element-resize-detector and now all is well.

**Comment by russplaysguitar** [comment]
:+1:

**Comment by bahuma20** [comment]
Still having the issue, other example: http://jsbin.com/bimotoyoyo/edit

**Comment by marcj** [comment]
Works for me in Chrome, Safari and Firefox @ OSX. Maybe the newest version just fixed it. Could you please provide more information about that topic? browser, OS, and if this issue is still open.
