### ISSUE TITLE
Bower does not recognize releases past 0.0.2

### ISSUE THREAD

**Issue by derekmooney** [marcj/css-element-queries#50]
Because of the way you're tagging now, bower cannot pull down v0.2 directly. I was able to work around this by using this notation in bower:

    "css-element-queries": "marcj/css-element-queries#v0.2"

But you'd probably prefer that people access the latest releases by default, rather than the older ones.

**Comment by marcj** [comment]
What is wrong with `v0.2` and bower?

**Comment by derekmooney** [comment]
I am able to use "v0.2" as the bower string, but when I use "0.2" as the bower version, I get

bower css-element-queries#0.2                                        ENORESTARGET No tag found that was able to satisfy 0.2

Additional error details:
Available versions: 0.0.2, 0.0.1

So it doesn't necessarily know about v0.2.

**Comment by etimberg** [comment]
The issue is that [bower.json](https://github.com/marcj/css-element-queries/blob/master/bower.json#L3) still lists the version as 0.0.2 rather than 0.2
