### ISSUE TITLE
couple of improvements on the code structure

### ISSUE THREAD

**Issue by normanzb** [marcj/css-element-queries#51]
Hey there,

I just made some changes in the fork and wondering if you are interesting in merge the changes.
the fork is here: https://github.com/normanzb/css-element-queries.

basically what it does is:

1. Separate the ResizeSensor from Element Queries because I think it will be reusable on its own.
2. Also made a few small changes to make ResizeSensor generate less number of 'function instances', so theoretically its faster and less memory consumption. 
3. Add AMD header so that it will be more friendly to people who is using AMD loader.
4. Gruntfile to do merging, compressing and bumping version number

Please let me know what do you think about the changes, I am willing to send the pull request and transfer the ownership if you are agree with the changes.

If otherwise please close the thread, thanks!

**Comment by marcj** [comment]
Thanks @normanzb, but I don't like to bind this library to any particular module loader.Also point 1-2 is not necessary, except you found some serious performance issues.

Point 4 is something I'd like to have more, but I prefer gulp over grunt :P Thanks anyway!
