### ISSUE TITLE
Not able to access "this" once ResizeSensor event is called

### ISSUE THREAD

**Issue by jonathanGB** [marcj/css-element-queries#56]
I'm not able to access "this" once the event is launched. Is there a way to solve this?

    new ResizeSensor($('#designDivs div.active div'), function() {
        // access $(this).parent('div').children('.row1');
    });

**Comment by marcj** [comment]
We don't bind the given callback to another context, so you need to do it on your own:

```javascript
var div = $('#designDivs div.active div');
new ResizeSensor(divs, function() {
    div.parent('div').children('.row1');
});
```

**Comment by jonathanGB** [comment]
Ok. Problem is I need to do a condition depending on what the specific div that is resizing has as a class. 

new ResizeSensor($activeDesignDiv, function() {
			if ($(this).hasClass('row1'))
				changeNoteSpecificsDiv($(this).parent('div').children('.row1'));
			else if ($(this).hasClass('row2'))
				changeNoteSpecificsDiv($(this).parent('div').children('.row2'));
		});

If it's not part of the current library, is there some doc you could suggest me that could help me store that reference? 

Thanks!

**Comment by marcj** [comment]
If you have a list of elements which need to be monitored each on its own, then you need to register for each element a new listener (which is anyway done by the library internally) instance.

```javascript
$activeDesignDiv.map(function(div) {
    var row = $(div).parent('div').children($(div).hasClass('row1') ? '.row1' : '.row2');
    new ResizeSensor(div, function() {
        changeNoteSpecificsDiv(row);
    });
});
```

**Comment by jonathanGB** [comment]
Right, thanks!

Just had to change the top to 
$.map($activeDesignDiv, function(div) {
