### ISSUE TITLE
Specify which CSS file to parse

### ISSUE THREAD

**Issue by nova-ind** [marcj/css-element-queries#57]
First off, let me say you've done a great job with this, it feels like native media queries.

I was wondering if there is a way to only parse a separate stylesheet containing the element queries. I'm seeing about 100ms execution time in the chrome profiler related to ElementQueries. Not exactly surprising, considering my CSS is about 600KB total, including Bootstrap and other plugins.

Cheers!

**Comment by marcj** [comment]
`CSS is about 600KB total`, wow. Why not clean up your styles? There's no filter currently implemented you can use to limit the parsing to some particular stylesheet files.
