### ISSUE TITLE
Does not work on IE10/11

### ISSUE THREAD

**Issue by rhuynh** [marcj/css-element-queries#60]
Responsiveness fails to work on IE10/11.  Have not tested in older versions.  This is from the latest code on main.

Demo:
http://plnkr.co/edit/wahIhtj2XmNgkyLmBSc6?p=preview

Drag the Demo 2 resizer.  
Observe that in Chrome/Firefox, that the boxes stack and the color changes from black to blue
Observe that same functionality fails on IE10/11.

**Comment by gbabula** [comment]
@rhuynh you're example is incorrect - if you update your CSS and markup to match the example provided you will see it works correctly in IE10/11.

__View this in IE10/11__
http://plnkr.co/edit/YZdHAT?p=preview

__Example__
https://github.com/marcj/css-element-queries/blob/master/test/index.html

**Comment by rhuynh** [comment]
@gbabula thanks for the example, but i noticed the only difference btwn your example and mine is that you named your css classes in all lowercase.  whereas mine is using mixed casing.  it is this use of mix-casing that is causing the bug in IE.  This bug is happening on the Edge browser as well.

here's my pull request to address the problem (note line 206, we're not replacing rules w/ the lowercase form):
https://github.com/rhuynh/css-element-queries/pull/1/files

**Comment by gbabula** [comment]
Good catch @rhuynh - I try to avoid uppercase characters all together in my CSS so I guess I was able to side-step this issue.

**Comment by chrisrichard** [comment]
I'm seeing a different issue where IE returns the CSS rule as:

`[max-width~="640px"].test-widget`

instead of 

`.test-widget[max-width~="640px"]`

which messes up the regex match and ultimately causes the element query styles to not be applied..

**Comment by czebe** [comment]
I'm experiencing the same problem on IE10/11 as @chrisrichard . Any recommendations for a workaround?

**Comment by phearlez** [comment]
I'm about to disable this entirely for IE loads because I'm seeing huge times spent in RegExp

**Comment by marcj** [comment]
Thanks to @wickning1, we've now merged two pull-requests which should fix your issues here. #78 #79 

Could you all please install current master and confirm whether your issue is fixed?

**Comment by phearlez** [comment]
Seems to fix my issue! Thanks.

**Comment by rhuynh** [comment]
Latest from master does indeed fix this bug for me.  Thanks

**Comment by marcj** [comment]
Great thanks guys :)
