### ISSUE TITLE
Add Minified JS file to the repo

### ISSUE THREAD

**Issue by TehBakker** [marcj/css-element-queries#73]
Would be great if the minified version of the Js were available directly from the repo.

**Comment by marcj** [comment]
I actually don't like that. If you need to reduce the size of such a small library even further, you should invest the time to build a Gulpfile or something else because chances are very high that this is not the only library in your website which needs to be minified.

**Comment by TehBakker** [comment]
Not really sure why you are so against it, as most JS library do that.
Either way I minified it myself.

**Comment by marcj** [comment]
For me a git repository should not contain stuff you can either build yourself or download somewhere else :)
