### ISSUE TITLE
The ResizeSensor breaks fixed positions

### ISSUE THREAD

**Issue by paya-cz** [marcj/css-element-queries#80]
The `attachResizeEvent` has a code

    if (!{fixed: 1, absolute: 1}[getComputedStyle(element, 'position')]) {
        element.style.position = 'relative';
    }

Which breaks my `position: fixed; width: 100%` header bar on IE11. What is the purpose of this code? Just commenting it out fixes the issue and doesn't seem to cause problems.

**Comment by marcj** [comment]
Well, the element needs to be absolute or fixed positioned. Obviously at the time ElementQueries runs it doesn't detect your element as `fixed`. Either that or that check for fixed doesn't work in general.

**Comment by paya-cz** [comment]
After debugging my specific case some more, the code seems correct. Sorry for the issue report. I would however suggest a change to:

    if (!{fixed: 1, absolute: 1, relative: 1}[getComputedStyle(element, 'position')]) {
        element.style.position = 'relative';
    }

Because I change the position using media queries (sometimes it's fixed, sometimes it's relative), hard-coding the position to 'relative' in original code prevents the browser from applying 'fixed' when the relevant media query comes into play. This can however be worked around using `!important` so it's not a big deal.

**Comment by marcj** [comment]
Well if the code detects that it is already relative then there is not need to set it again to relative :) Guess this is fixed then? Please reopen this issue if you keep having issues with it.

**Comment by paya-cz** [comment]
Yes exactly, no need to set it to relative if it is already relative. The [most recent version](https://github.com/marcj/css-element-queries/blob/feaa88928ab60989800c8f1e5485853c1d953013/src/ResizeSensor.js#L80) however doesn't check for 'relative'.

Current code as of `feaa889`:

    if (!{fixed: 1, absolute: 1}[getComputedStyle(element, 'position')]) {

Proposed code:

    if (!{fixed: 1, absolute: 1, relative: 1}[getComputedStyle(element, 'position')]) {

**Comment by marcj** [comment]
Why should it check for relative, just to make it then relative? I don't see the point with it :P

**Comment by paya-cz** [comment]
As written, the `if` block is not executed if the element position is either fixed, absolute or relative. Notice the `!` in the condition expression. So the proposed code sets the position to relative if and only if the position is neither fixed, absolute nor relative.

**Comment by marcj** [comment]
oh lol, sorry, now I got it :) thanks for your patience. I'm going to fix it later :)
