### ISSUE TITLE
Track dynamically added elements

### ISSUE THREAD

**Issue by HugoHeneault** [marcj/css-element-queries#81]
Hi there, 

I'd like to use css-elements-queries in an angular project, but it seems that dynamically added elements are not tracked.
Is it a way to achieve that?

Thanks!

**Comment by marcj** [comment]
Currently not, but I'm planing to have an angular module for that.

**Comment by emendelski** [comment]
@marcj Any news about that module? :)

**Comment by marcj** [comment]
Not yet, I guess next WE I'll find time for the angular side of this :)

**Comment by HugoHeneault** [comment]
Awesome!!

**Comment by emendelski** [comment]
:+1:

**Comment by davidspiess** [comment]
I have the same problem but with react :)

**Comment by JSteunou** [comment]
I have the same problem but with backbone.marionette :p 

After reading how it works, I understand the concept is mostly reading CSS rules, find out which one are element queries, then applying the correct one. End. Job done.

Another cool method is `update`, which launches that process again.

For components / views driven application, I think our need at the API level would be a generic `addElement(s)` that would do:
* parse css rules
* find out those matching the element
* find out if it's just element or image
* call the correct setup

Then maybe we would need a public by element `detach` method (the current and only public one detach *all* the elements), when closing / destroying app components / views. But I'm still not sure about this one. I see references to `withTracking` option, which put element into an Array, without seeing how or when it's use, but even without this option, ResizeSensor is used, so maybe in all cases we would need to call `detach`

**Comment by marcj** [comment]
Yeah that's a tough nut, I'm not sure how to implement this yet. `withTracking` has the tremendous disadvantage that the garbage collector doesn't work correctly when the EQ lib has also a reference to the DOM element. Best way would be that EQ doesn't know anything about the environment but the particular framework like angular/react/etc have a integration which calls EQ each time they update the DOM.

**Comment by JSteunou** [comment]
maybe this gist can give you some idea https://gist.github.com/JSteunou/e3fa78c2c86b467f7fc1

**Comment by marcj** [comment]
What should we see in this gist?

**Comment by JSteunou** [comment]
Another way to init element queries. Instead of parsing CSS, which could be resource consuming on big app, and does not play well with dynamic element on web app (think about not shown or present in DOM yet element), and parsing again by calling `update` when we finally add some elements, I propose to add an API that allow to manually add element with its breakpoints definition.

In my example I created `EQ.addBreakpoints(document.querySelector('.widget-name'), {'min-width': ['400px', '600px', '700px']});`

This allow me to create view (in term of backbone), call the lib when the view is attached, let it work thanks to `ResizeSensor`, and call `remove` when the view is remove from the DOM or when I dont need watchdog anymore.

The point is, exposing API is the key to make this lib playing nice with web app, whatever the framework is used.

**Comment by marcj** [comment]
I agree, we need a public method which can be used by all of those frameworks. Its then up to he a 'element-queries-hook' of the particular framework in which events/circumstances this element query method (probably the `init` method) is being called. I think #95 is the first step in this direction.

**Comment by JSteunou** [comment]
I'm sorry that's not it. Like I said crawling the all document is perf consuming. Better to make a real API than a hook to call `init` again.

The concept in my gist is to attach to each DOM an ElementQuery and a ResizeSensor instance, but the process of attachment is not done by parsing the page, it's done either manually, or either by tiers code.

That tiers code could be the parser. Today both are in the same module in your library, and tightly coupled. The idea is to unbind them, so one can just use manually EQ on the Node he needs, and one can use EQ parser which will parse his page and auto set EQ on each Node it will find by parsing.

Making the parser use the library through API, and not making the parser having a hook to add pseudo API.

**Comment by marcj** [comment]
> Like I said crawling the all document is perf consuming

No one talked about that. See #95, this doesn't scan complete document, but only changed nodes.

> The concept in my gist is to attach to each DOM an ElementQuery and a ResizeSensor instance, but the process of attachment is not done by parsing the page, it's done either manually, or either by tiers code.

Exactly what the goal is.

There is no such thing as `real API` or `pseudo API`. If css-element-queries says that a method (doesn't matter if its called `init`, `update` or stuff like that) to do this kind of manually searching new elements that need to be tracked, then this is the `official real API`.

**Comment by JSteunou** [comment]
Ok I read it wrong, thought `init` will always parse all the document and CSS.

What you describe indeed feet as a `add`. How about a `remove` now? A way to call `ResizeSensor#detach`.

Also when talking about pseudo API, I was referring the hook you talked above, but it seems I go it wrong. I though you were talking about it as the main entry point for a thing like a `add`.

**Comment by marcj** [comment]
No worries! :) Yes, a `remove` would then also be necessary.

**Comment by patrickmichalina** [comment]
@marcj What is the current best approach to use this library within Angular 2? This is the only decent project I can find that deals with the idea of responsive web components based on their own container, not the main view-port (media queries).

**Comment by theupmachine** [comment]
@marcj Did you finally manage to create an angular 1.x library for the project?

**Comment by marcj** [comment]
@patrickmichalina I don't think there's a general approach including css-element-queries into angular so "it just works". Currently, you need to deal with it yourself in `link` method, everytime you manipulate the DOM tree.

@theupmachine nope.

**Comment by romshark** [comment]
I experience the same deficiency when using regular Angular2 router. When the view is switched queries stop working. Any way to get it to work?

**Comment by marcj** [comment]
Fixed in upcoming 1.0.0 version using animationstart hack (that will be released soon).
