### ISSUE TITLE
How does one make this function with NPM and webpack?

### ISSUE THREAD

**Issue by biznickman** [marcj/css-element-queries#82]
The only documentation states to require the `ResizeSensor.js` and `ElementQueries.js` in the footer but I want to package it with my own distributed app. 

It doesn't appear to be supported in the current version?

**Comment by marcj** [comment]
Newest version has package support.

**Comment by kobeaerts** [comment]
I'm sorry but it still isn't working with webpack/babel import can you maybe put an example online?

**Comment by phil-lgr** [comment]
I use ES6 with Babel + Webpack
```
import ResizeSensor from 'css-element-queries/src/ResizeSensor';
import ElementQueries from 'css-element-queries/src/ElementQueries';
```

**Comment by kobeaerts** [comment]
I keep getting ''paragraphs.js:233 Uncaught TypeError: Cannot set property 'ElementQueries' of undefined"

**Comment by kobeaerts** [comment]
The strange thing is, it only fails at the ElementQueries, ResizeSensor loads just fine :/

**Comment by kobeaerts** [comment]
Ok, seems an React issue..
