### ISSUE TITLE
Test current master on all IE version

### ISSUE THREAD

**Issue by marcj** [marcj/css-element-queries#86]
With newest modifications (performance improvements) we should make sure that current master is still working for all browsers.

**Comment by jyrkij** [comment]
There are problems on IE 11 & Edge when thigs aren't visible, see https://www.pentik.com/en/vrt10000504 Add to cart -buttons. When the plate size is changed 24 cm cannot be added to cart for some reason. Resizing the window or causing repaints in other ways 'fixes' this.

**Comment by marcj** [comment]
@jyrkij already tracked at https://github.com/marcj/css-element-queries/issues/46

**Comment by jyrkij** [comment]
This is different from #46 as we hack around it with not setting `display: none;` and setting `height` etc. to 0 instead. As you can see some of the Add to cart -buttons do work. What seems to work (hack again) is to set e.g. `z-index` to some random value to trigger ResizeSensor and after a few hundred milliseconds reset it.

**Comment by marcj** [comment]
So the differences is it is invisible through height=0? Does it work with height=1? Is this directly relateed to this issue #86 => master branch, or does it work with v0.3.2?

**Comment by jyrkij** [comment]
3/4 seem to work initially. The on that doesn't work with 0 height doesn't work with `height: 1px;`. And v0.3.2 doesn't work neither. So I think I hijacked the wrong thread after all. Sorry for that!

**Comment by marcj** [comment]
Mh interesting, if you find new information/clues please let me know, so I can start addressing it without doing it from scratch :)
