### ISSUE TITLE
imported style sheets are not read on init

### ISSUE THREAD

**Issue by eshperber** [marcj/css-element-queries#87]
I noticed that in IE9  @import style sheet rules are not being read 

added: 

`if (document.styleSheets[i].imports.length > 0) {
                    try {
                        for (var k = 0, l = document.styleSheets[i].imports.length; k < l; k++) {
                            readRules(document.styleSheets[i].imports[k].cssRules || document.styleSheets[i].imports[k].rules || document.styleSheets[i].imports[k].cssText);
                        }} catch (e) {
                        if (e.name !== 'SecurityError') {
                            throw e;
                        }
                    }
                }`

to solve this on my own app. probably a better way of doing it but it worked.

**Comment by marcj** [comment]
Good catch! Would you like to provide a pull-request with your changes?

**Comment by eshperber** [comment]
yes thank you.
