### ISSUE TITLE
Not CJS builder friendly enough

### ISSUE THREAD

**Issue by JSteunou** [marcj/css-element-queries#89]
I'm using webpack and doing `require('css-element-queries');` dont go so well because of https://github.com/marcj/css-element-queries/blob/master/src/ElementQueries.js#L20 and your `index.js`.

~~`this` is undefined because there is not context. You should use `this.ElementQueries` in a `else` condition after checking `module` and `module.exports`.~~  ok already got a `window.ElementQueries` so don't really know what this kind of export is for...

second, it could be nice to export both EQ and RS from the `index.js` which would bring a nicer API to this lib when required in a modern modular project.

**Comment by marcj** [comment]
thanks, merged :)

**Comment by JSteunou** [comment]
thank you, this lib sounds very promising, really nice work! Do you think you'll publish a new release with this fix pretty soon?
