### ISSUE TITLE
multiple pseudo class

### ISSUE THREAD

**Issue by r043v** [marcj/css-element-queries#91]
hi, thanks for your nice library,

i'm trying to addapt one of [my library](https://github.com/r043v/agres) to use elements query,
it seem that none of the rules that use two pseudo class selector works, could you have a look ?

[here](http://agres.dude.pm/css-element-queries/) is my test page, and [here](http://agres.dude.pm/) the same with classic media query

**Comment by r043v** [comment]
my bad it's your use of the div .resize-sensor who up the elements numbers and all of my code depend of this.

**Comment by r043v** [comment]
fixed using a wrap where resize sensor attached on, and resize sensors removed from all wrap childrens

maybe allow an option to select where resizeSensor will insert his sensors,
ie, using isCollectionTyped to recurse about childrens or attach to parents/specific filter etc ?

**Comment by marcj** [comment]
How would you define such a option where the resizeSensor places the sensor?

**Comment by r043v** [comment]
a hard writed class or data attribute would said to stop iterate and place the sensors at the actual place nevermind the current node is could be simple and efficient
