### ISSUE TITLE
function getEmSize only appears to work

### ISSUE THREAD

**Issue by Schepp** [marcj/css-element-queries#92]
The function `getEmSize` only appears to work when using rem units because it falls back to the default 16px value, which most roots have. To get it working, and especially get it working with em units, it needs to be changed into that:

```js
function getEmSize(element) {
    if (!element) {
        element = document.documentElement;
    }
    var styles = getComputedStyle(element);
    return parseFloat(styles['fontSize']) || 16;
}
```

**Comment by marcj** [comment]
Thanks for reporting this. Would you like to send a pull-request with your fixes?

**Comment by Schepp** [comment]
Will do! Found another bug in `convertToPx`. First line should be:

```js
var units = value.replace(/\s*/,'').replace(/[0-9\.]*/, '');
```

**Comment by marcj** [comment]
Good catch! Looking forward to your pull-request :)

**Comment by JSteunou** [comment]
I think this is fixed by https://github.com/marcj/css-element-queries/commit/7c45c30ce958394f6d09f12c79be6f18fbc426f3
