### ISSUE TITLE
How to register elements that did not exist upon window load

### ISSUE THREAD

**Issue by jvskriubakken** [marcj/css-element-queries#99]
Hi,

and first of all for making a great library!

I've so far only used the ResizeSensor and is very happy with it.
I'm working on a "office UI" where every dom element is created using javascript after window.onload.
And some parts of the UI is created at much later time (from user interaction). Am I right when I say that ElementQueries will not be enabled for elements created/added to the document after window.onload. If so, is there a way to make ElementQueries aware of new elements?

Thanks for any help or guidance!

Jørund Vier Skriubakken

**Comment by jvskriubakken** [comment]
I see function ElementQueries.setupElement exists.
Would it be enough to call this function with element and correct options?

**Comment by marcj** [comment]
No, please use ElementQueries.init(). This is executing all known css rules at the DOM to fetch newly created elements and attach only there the magic.

**Comment by jvskriubakken** [comment]
OK. Is it safe to call it many times?

**Comment by marcj** [comment]
Yes

**Comment by jvskriubakken** [comment]
OK. Thanks :+1.
I will try.
